name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # 选择合适的 .NET 版本

      - name: Restore dependencies
        run: dotnet restore NsoElfConverterDotNet/NsoElfConverterDotNet.csproj

      - name: Build project
        run: dotnet build NsoElfConverterDotNet/NsoElfConverterDotNet.csproj --configuration Release

      - name: Publish project
        run: dotnet publish NsoElfConverterDotNet/NsoElfConverterDotNet.csproj --configuration Release --output ./output

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: NsoElfConverter
          path: ./output
