name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'  # 使用 .NET Core 3.1

      - name: Restore dependencies
        run: dotnet restore NsoElfConverterDotNet.Console/NsoElfConverterDotNet.ConsoleApp.csproj

      - name: Build project
        run: dotnet build NsoElfConverterDotNet.Console/NsoElfConverterDotNet.ConsoleApp.csproj --configuration Release

      - name: Publish project
        run: dotnet publish NsoElfConverterDotNet.Console/NsoElfConverterDotNet.ConsoleApp.csproj --configuration Release --output ./output

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NsoElfConverterConsole
          path: ./output
