name: Build NsoElfConverterDotNet (Windows x64 Release)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v2
        with:
          version: '3.1.x'

      - name: Restore dependencies
        run: dotnet restore NsoElfConverterDotNet.sln

      - name: Publish Release | x64
        run: |
          dotnet publish NsoElfConverterDotNet.sln --configuration Release --runtime win-x64 --self-contained false -p:PublishSingleFile=true

      # 修改为使用 v2 版本
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NsoElfConverterDotNet-Win-x64-Release
          path: bin/Release/netcoreapp3.1/win-x64/publish/
